site_name: 營造業線上申請系統指南
site_url: https://heke0621.github.io/online_system_tutorial/
theme:
  name: material
  language: zh-Hant
  icon:
    admonition:
      <type>: octicons/alert-16 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.top
extra_css:
  - 'css/custom.css'
  - 'css/simpleLightbox.min.css'

extra_javascript:
  - 'js/jquery-3.2.1.min.js'
  - 'js/simpleLightbox.min.js'
  - 'js/custom.js'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - markdown.extensions.attr_list

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:heke0621@gmail.com
      name: 如需勘誤內容，請聯繫作者



nav:
 - 關於線上申請系統: index.md
 - 如何註冊線上申請系統: register.md
 - 土木包工業線上申請: 
    - 籌設許可申請: Civil_Contracting_Industry/Contractors_Registration.md
    - 許可期限展延申請: Civil_Contracting_Industry/Contractors_Registration_2.md
    - 申領登記: Civil_Contracting_Industry/receive_manual.md
    - 變更資本額申請: Civil_Contracting_Industry/change_capital.md
    - 變更地址申請: Civil_Contracting_Industry/change_address.md
    - 縣市移轉(跨縣市變更地址)申請: Civil_Contracting_Industry/change_city.md
    - 變更負責人申請: Civil_Contracting_Industry/change_person.md
    - 變更印鑑申請: Civil_Contracting_Industry/change_stamp.md
    - 變更公司名稱申請: Civil_Contracting_Industry/change_name.md
    - 變更公司組織申請: Civil_Contracting_Industry/change_organization.md
    - 手冊或證書補發(續發)申請: Civil_Contracting_Industry/receive_manual_2.md
    - 複查申請: Civil_Contracting_Industry/review.md
    - 停業、歇業、復業申請: Civil_Contracting_Industry/stop_work.md
 - 綜合營造業線上申請:
    - 籌設許可申請: General_Construction/Contractors_Registration.md
    - 許可期限展延申請: General_Construction/Contractors_Registration_2.md
    - 申領登記: General_Construction/receive_manual.md
    - 變更專任工程人員(包含技師因故不能執行業務報請備查): General_Construction/change_engineer.md
    - 晉升等級申請: General_Construction/upgrade.md
    - 變更資本額申請: General_Construction/change_capital.md
    - 變更地址申請: General_Construction/change_address.md
    - 縣市移轉(跨縣市變更地址)申請: General_Construction/change_city.md
    - 變更負責人申請: General_Construction/change_person.md
    - 變更印鑑申請: General_Construction/change_stamp.md
    - 變更公司名稱申請: General_Construction/change_name.md
    - 變更公司組織申請: General_Construction/change_organization.md
    - 手冊或證書補發(續發)申請: General_Construction/receive_manual_2.md
    - 複查申請: General_Construction/review.md
    - 停業、歇業、復業申請: General_Construction/stop_work.md
 - 專業營造業線上申請:
    - 籌設許可申請: Specialized_Construction/Contractors_Registration.md
 - 淨值申報線上申請(114年度試辦): civ100m.md
  
    
